### ISSUE TITLE
Can't find question.jsonl

### ISSUE THREAD

**Issue by running-alpaca** [AdaCheng/EgoThink#12]
Hello!
I meet a promblem when I ran gen_judgment.py. The error is as follows:
FileNotFoundError: [Errno 2] No such file or directory: 'data/mt_bench/question.jsonl'
I wonder where could I find the question.jsonl file, or maybe I could get this file from some where? 
Could you please give more details about this file?
Thank you!

**Comment by AdaCheng** [comment]
When you run the inference code, this "question.jsonl" is automatically generated.
For example, when you use the following inference script, the questions corresponding to the inference answers will automatically generated under the directory 'answer/Object/question.jsonl'. So you do not need to download this file. You need to run the models to generate this file.
```
python eval.py \
    --model_name $MODEL \
    --annotation_path /Object/annotations.json \
    --answer_path /answer/Object \
    --batch_size 1 \
    --device $DEVICE
```

**Comment by running-alpaca** [comment]
Thank you for your reply. I find this file in my folder. I didn't mention it.
Thank you very much!
