### ISSUE TITLE
about the prompts setup

### ISSUE THREAD

**Issue by BIT-MJY** [AdaCheng/EgoThink#6]
Hi @AdaCheng and @PhoenixGS, 

Thank you for your nice contribution! I'm a newcomer to this field. Could you introduce the motivation for designing different "general prompts" for different VLM in your experiments (Appendix C)? Thanks!

**Comment by AdaCheng** [comment]
Thank you for your attention. Due to the different setups of the original system prompts and the varied training data distributions of different VLMs, we need to design suitable prompts for each VLM to bring out their potentials and ensure a fair comparison.
