### ISSUE TITLE
 Unable to reproduce the results reported for LLava-v1.5-7B in your paper

### ISSUE THREAD

**Issue by hongming21** [AdaCheng/EgoThink#7]
Hi，
I am currently testing LLava-v1.5-7B on the dataset you provided, but I found a discrepancy between my results and those reported in your paper. Initially, I thought the score was the sum of all questions, but I realized that subsets like 'Object_affordance' have only 50 questions, while the LLava-v1.5-7B score you provided is 54,  it seems not to be a simple sum. I couldn't find the part of your code that handles the score calculation. Could you please explain how the scores in your paper were calculated or point me to the relevant code? 

By the way, there seems to be an issue with the module references in the LLava part of the released code. Running it directly results in a 'no module llava' error, which requires modification of the import paths. Thank you.

**Comment by AdaCheng** [comment]
Thank you for your questions.

1. The current performance of LLava-v1.5-7B differs from the version we released in 2023. Some modules have changed in the repo of LLava-v1.5, affecting performance. Our latest study shows LLava-v1.5-7B achieving a performance score of 51.2. We will double-check this and update the performance metrics in our repository and on our homepage soon.
2. We calculate accuracy as follows: 27 (total score) / 50 (total number) = 54%.
3. The 'No module llava' error might be due to changes in the new version of the LLava package. We will release a requirements.txt file to address this issue shortly.

If you have any further questions, please let us know.

**Comment by hongming21** [comment]
> Thank you for your questions.
> 
> 1. The current performance of LLava-v1.5-7B differs from the version we released in 2023. Some modules have changed in the repo of LLava-v1.5, affecting performance. Our latest study shows LLava-v1.5-7B achieving a performance score of 51.2. We will double-check this and update the performance metrics in our repository and on our homepage soon.
> 2. We calculate accuracy as follows: 27 (total score) / 50 (total number) = 54%.
> 3. The 'No module llava' error might be due to changes in the new version of the LLava package. We will release a requirements.txt file to address this issue shortly.
> 
> If you have any further questions, please let us know.

Thank you for your prompt reply!

I still want to confirm which conv_template was used during the generation of llava-v1.5-7b. In the **model.llava.conversation** file in your codebase, I found two modified conv_temp : **conv_llava_v1** and **conv_llava_v1_planning**. Could you please confirm if these two were the conv_temp used during the generation of llava-v1.5-7b?

**Comment by AdaCheng** [comment]
conv_llava_v1 is used for the usual generation, while conv_llava_v1_planning is designed specifically for the planning dimension.

**Comment by hongming21** [comment]
> conv_llava_v1 is used for the usual generation, while conv_llava_v1_planning is designed specifically for the planning dimension.

Thank you for your help. I have successfully reproduced the result of 51.2. However the cost of a single evaluation API call is unexpectedly high :innocent:. Could you please share the approximate cost of evaluating a complete dataset with gpt-4?

**Comment by AdaCheng** [comment]
Thanks for your question. GPT-4 as the evaluator inevitably is expensive and unstable. Therefore, we have specifically fine-tuned an open-source LLM to evaluate and will release it soon.
